# Generated by Django 2.2.4 on 2019-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подробное описание'),
        ),
    ]
